dist: xenial
sudo: false

language: go
go_import_path: gopkg.in/vmarkovtsev/go-lcss.v1
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x

before_install:
  - if [[ $TRAVIS_GO_VERSION != 1.8.* ]]; then go get -v golang.org/x/lint/golint; fi

script:
  - set -e
  - test -z "$(gofmt -s -l .)"
  - go vet ./...
  - if [[ $TRAVIS_GO_VERSION != 1.8.* ]]; then golint -set_exit_status ./...; fi
  - go test -v -cpu=1,2 -coverprofile=coverage.txt -covermode=count gopkg.in/vmarkovtsev/go-lcss.v1/...
  - set +e
  - if [[ $TRAVIS_GO_VERSION = 1.11.* ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
